enabling branch deployments

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -1,21 +1,75 @@
 #!/bin/bash
 
-# exit on error
+# run script/deploy -h for help
+# ~/pihole/script/deploy -r="${{ steps.branch-deploy.outputs.ref }}" -f="${{ steps.branch-deploy.outputs.fork_checkout }}" -d="pihole" -n="${{ steps.branch-deploy.outputs.fork_full_name }}"
+
 set -e
 
-# get the directory of this script
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-cd $DIR
+BASE_BRANCH="main"
 
-# get the repo directory
-REPO_DIR=$(git rev-parse --show-toplevel)
-cd $REPO_DIR
+function usage()
+{
+    echo -e "\t ============================== script/deploy usage =============================="
+    echo -e "\t-h --help               : displays help message"
+    echo -e "\t-f --fork               : the checkout command to use if a fork"
+    echo -e "\t-n --fork-full-name     : the full name of the fork source in 'org/repo' format"
+    echo -e "\t-d --dir                : the directory to enter for the deployment"
+    echo -e "\t-r --ref                : ref to deploy"
+}
 
-# run git pull and if there are changes, restart the server
-pull_result=$(git pull)
-if [[ $pull_result == *"Already up to date."* ]]; then
-    echo "No changes to pull"
-else
-    echo "Changes pulled, restarting server"
-    make run
+while [ "$1" != "" ]; do
+    PARAM=`echo $1 | awk -F= '{print $1}'`
+    VALUE=`echo $1 | awk -F= '{print $2}'`
+    case $PARAM in
+      -h | --help)
+        usage
+        exit
+        ;;
+      -f | --fork)
+        fork=$VALUE
+        ;;
+      -n | --fork-full-name)
+        fork_full_name=$VALUE
+        ;;
+      -d | --dir)
+        dir=$VALUE
+        ;;
+      -r | --ref)
+        ref=$VALUE
+        ;;
+      *)
+      echo "ERROR: unknown parameter \"$PARAM\""
+      usage
+      exit 1
+      ;;
+    esac
+    shift
+done
+
+# If a deployment dir is specified, enter it
+if [[ -n $dir ]]; then
+  cd ~/$dir
 fi
+
+# If a fork deployment is requested use the fork branch
+if [[ -n $fork ]]; then
+  echo "fork deployment requested"
+  forkarray=($fork)
+  git checkout -b $fork || git fetch --all && git reset --hard origin/$BASE_BRANCH && git branch -D $fork && git checkout -b $fork
+  git pull "https://github.com/$fork_full_name.git" ${forkarray[1]}
+else
+  echo "branch deployment requested"
+  git fetch --all
+  git reset --hard origin/$ref
+fi
+
+echo "[-] Killing old docker processes"
+sudo docker compose down --remove-orphans -v -t 1
+
+echo "[i] Building docker container"
+sudo docker compose up --build -d
+
+echo "[+] Containers are now running!"
+
+# for runway
+echo remote-deploy-success
