update deploy script

diff --git a/script/deploy b/script/deploy
--- a/script/deploy
+++ b/script/deploy
@@ -1,3 +1,29 @@
 #!/bin/bash
 
-echo "test"
+# exit on error
+set -e
+
+# get the directory of this script
+DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+cd $DIR
+
+# get the repo directory
+REPO_DIR=$(git rev-parse --show-toplevel)
+cd $REPO_DIR
+
+# pull the latest release tag and check to see if it's different from the current tag
+git fetch --tags
+LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
+CURRENT_TAG=$(git describe --tags)
+
+# if the tag is different, then deploy
+# a deployment is a git checkout (force) of the latest tag and a restart of the docker compose stack using the latest code
+if [ "$LATEST_TAG" != "$CURRENT_TAG" ]; then
+    echo "New release found: $LATEST_TAG"
+    echo "Updating to $LATEST_TAG"
+    # git checkout -f $LATEST_TAG
+    echo "Restarting docker compose stack"
+    make run
+else
+    echo "No new release found"
+fi
